combined_data_path: data/processed/combined_data.csv
mlflow_tracking_uri: mlruns
model_directory: model
model_filename: random_forest_model.pkl
model_params:
  max_depth: 15
  n_estimators: 250
n_lags: 4
run_id: 52e677cde1db411fb75ec5e5ddb817a2
start_year: 2020
target: Total_Release_Water
test_path: data/processed/test_processed.csv
train_path: data/processed/train_processed.csv
